### ISSUE TITLE
The type or namespace name 'CropImageView' could not be found

### ISSUE THREAD

**Issue by draugaslt** [mikescandy/Xamarin-Cropper#3]
Error CS0246: The type or namespace name 'CropImageView' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (SampleApp)

What did i missed?

**Comment by mikescandy** [comment]
not sure, haven't check this project in a while (although the library is working fine in a different project). will review and post back!

**Comment by mikescandy** [comment]
Hi, i just checked out the project and it runs fine on my machine. Would you be able to post the build output?

**Comment by mikescandy** [comment]
can't reproduce, closing.
