### ISSUE TITLE
Problem with not receiving cropped image

### ISSUE THREAD

**Issue by RomeoBeun** [mikescandy/Xamarin-Cropper#9]
I tried to follow the documentation but have been stuck on this part for a bit now

Here's my code

`       protected override void OnActivityResult(int requestCode, [GeneratedEnum] Result resultCode, Intent data)
    {
        if (requestCode == PickImageChooserRequestCode && resultCode == Result.Ok && data != null)
        {
            CropImage.ActivityResult result = CropImage.GetActivityResult(data);
            //Android.Net.Uri resultUri = result.Uri;
            Android.Net.Uri resultUri = data.Data;
            CropImage.Builder(resultUri).Start(this);//call and start the image cropper XamarinAndroidImageCropper https://github.com/mikescandy/Xamarin-Cropper
            Bitmap mBitmap = Media.GetBitmap(this.ContentResolver, resultUri);
            cropImageView.SetImageBitmap(mBitmap);
        }
        else
        {
            Toast.MakeText(this, "I ran into a problem", ToastLength.Long).Show();
        }
    }`

From this i do get the image but its always the full image not the cropped one like i want.

Let me know if you want to see more code or pictures of the app

**Comment by mikescandy** [comment]
haven't touched this in a long time! I'll have a look and see if I can help you :)

**Comment by mikescandy** [comment]
I hardly remember how this worked, but in the sample I see I used  
`var imageUri = CropImage.GetPickImageResultUri(this, data);
`
 instead of                 

`CropImage.ActivityResult result = CropImage.GetActivityResult(data);
`

Not sure if that could be the issue

**Comment by RomeoBeun** [comment]
> 
> 
> I hardly remember how this worked, but in the sample I see I used
> `var imageUri = CropImage.GetPickImageResultUri(this, data); `
> instead of
> 
> `CropImage.ActivityResult result = CropImage.GetActivityResult(data); `
> 
> Not sure if that could be the issue

Hey @mikescandy ,  thanks for your response i wil try this tomorrow. Wil let you know either way what happens

**Comment by RomeoBeun** [comment]
Hello aigan @mikescandy unfortunately it didnt change anything the project is on git if you want to reproduce would like to hear back [https://gitlab.com/RomeoBeun/findyourting](url)

Made the project public so you can acces it
Its on gitlab as im building a portfolio there

**Comment by mikescandy** [comment]
had a quick look.
you need to:
- change the cropimageview in content_main to be an ImageView (make the change also in your mainactivity0
- add this in ActivityOnResult:
`else if (requestCode == CropImage.CropImageActivityRequestCode)
            {
                CropImage.ActivityResult result = CropImage.GetActivityResult(data);
                if (resultCode == Android.App.Result.Ok)
                {
                    var resultUri = result.Uri;
                    Bitmap mBitmap = Media.GetBitmap(this.ContentResolver, resultUri);//Convert Uri to bitmap
                    cropImageView.SetImageBitmap(mBitmap);//set bitmap to view
                }
                else if ((int)resultCode == CropImage.CropImageActivityResultErrorCode)
                {
                    Toast.MakeText(this, "I ran into a problem", ToastLength.Long).Show();
                }
            }`

the flow is MainActivity=>FIlePicker=>Back to Main Activity (invoke onresult coming from picker) =>CropActivity=>Back to Main Activity (invoke onresult coming from picker, use a different request code) and display the cropped image

The library is working as expected, going to close this.

**Comment by RomeoBeun** [comment]
> 
> 
> had a quick look.
> you need to:
> 
>     * change the cropimageview in content_main to be an ImageView (make the change also in your mainactivity0
> 
>     * add this in ActivityOnResult:
>       `else if (requestCode == CropImage.CropImageActivityRequestCode) { CropImage.ActivityResult result = CropImage.GetActivityResult(data); if (resultCode == Android.App.Result.Ok) { var resultUri = result.Uri; Bitmap mBitmap = Media.GetBitmap(this.ContentResolver, resultUri);//Convert Uri to bitmap cropImageView.SetImageBitmap(mBitmap);//set bitmap to view } else if ((int)resultCode == CropImage.CropImageActivityResultErrorCode) { Toast.MakeText(this, "I ran into a problem", ToastLength.Long).Show(); } }`
> 
> 
> the flow is MainActivity=>FIlePicker=>Back to Main Activity (invoke onresult coming from picker) =>CropActivity=>Back to Main Activity (invoke onresult coming from picker, use a different request code) and display the cropped image
> 
> The library is working as expected, going to close this.

Wow it instantly worked the way u said to add it thank you so much have been stuck on this for a few days.
Just goes to show ive got a lot to learn stil.

Just to be sure i never meant to blame the library i was sure it was something from my side was just looking for help and who better then the person who would know the most about this.

Thanks aigan wil keep the project public check back in a week or 2 and try it out maybe, feedback is always welcome.
